import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import QRCode from 'react-qr-code';
import { Activity, ArrowDownUp, Check, ChevronRight, CircleHelp, Copy, Globe2, KeyRound, LayoutDashboard, Link2, LogOut, Menu, Plus, RefreshCw, Server, Shield, Trash2, Users, X } from 'lucide-react';
import './style.css';

type Item = Record<string, unknown> & { id: string };
type State = { revision: number; nodes: Item[] | null; people: Item[] | null; inbounds: Item[] | null; outbounds: Item[] | null; rules: Item[] | null; assignments: Item[] | null };
type Kind = 'nodes'|'people'|'inbounds'|'outbounds'|'rules'|'assignments';
type Field = { key: string; label: string; type?: 'text'|'number'|'datetime-local'|'select'|'textarea'|'checkbox'|'password'; options?: {value:string,label:string}[]; hint?: string };
const empty: State = {revision:0,nodes:[],people:[],inbounds:[],outbounds:[],rules:[],assignments:[]};
const plural: Record<Kind,string> = {nodes:'节点',people:'人员',inbounds:'入站',outbounds:'出口',rules:'分流规则',assignments:'订阅分配'};
const nav: {id:string;label:string;icon:React.ComponentType<{size?:number}>}[] = [
  {id:'overview',label:'总览',icon:LayoutDashboard},{id:'nodes',label:'VPS 节点',icon:Server},{id:'inbounds',label:'入站协议',icon:Globe2},{id:'outbounds',label:'出口与落地',icon:ArrowDownUp},{id:'rules',label:'分流规则',icon:Link2},{id:'people',label:'人员与额度',icon:Users},{id:'assignments',label:'订阅分配',icon:KeyRound}
];
async function api(path:string,method='GET',data?:unknown){const r=await fetch(path,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,credentials:'same-origin'});if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).trim()||r.statusText}`);return r.json()}
function str(v:unknown){return v==null?'':String(v)}
function bytes(v:unknown){const n=Number(v||0);if(!n)return '0 B';const i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return (n/1024**i).toFixed(i?1:0)+' '+['B','KB','GB','TB','PB'][i].replace('GB','MB').replace('TB','GB').replace('PB','TB')}
function date(v:unknown){if(!v||String(v).startsWith('0001'))return '—';return new Date(String(v)).toLocaleString('zh-CN')}
function App(){
  const [logged,setLogged]=useState<boolean|null>(null),[password,setPassword]=useState(''),[state,setState]=useState<State>(empty),[page,setPage]=useState('overview'),[dialog,setDialog]=useState<{kind:Kind,item?:Item}|null>(null),[reveal,setReveal]=useState<{title:string,token:string,url:string,deployCommand:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mobile,setMobile]=useState(false);
  const refresh=async()=>{try{const s=await api('/api/v1/state');setState(s);setLogged(true);setError('')}catch(e){if(String(e).includes('401'))setLogged(false);else setError(String(e))}};
  useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[]);
  const collections=useMemo(()=>({nodes:state.nodes||[],people:state.people||[],inbounds:state.inbounds||[],outbounds:state.outbounds||[],rules:state.rules||[],assignments:state.assignments||[]}),[state]);
  const find=(kind:Kind,id:unknown)=>collections[kind].find(x=>x.id===id);
  const label=(kind:Kind,id:unknown)=>str(find(kind,id)?.name||find(kind,id)?.id||id||'—');
  const onSave=async(kind:Kind,item:Item|undefined,body:Record<string,unknown>)=>{setBusy(true);setError('');try{const url=item?`/api/v1/${kind}/${item.id}`:`/api/v1/${kind}`;const result=await api(url,item?'PUT':'POST',body);setDialog(null);await refresh();if(result.token){setReveal({title:`${plural[kind]}已创建`,token:result.token,url:result.subscription_url||'',deployCommand:result.deploy_command||''})}}catch(e){setError(String(e))}finally{setBusy(false)}};
  const remove=async(kind:Kind,id:string)=>{if(!confirm(`确定删除这个${plural[kind]}？请先移除引用它的规则或分配。`))return;try{await api(`/api/v1/${kind}/${id}`,'DELETE');await refresh()}catch(e){setError(String(e))}};
  const rotate=async(kind:'nodes'|'people',id:string)=>{if(!confirm('旧令牌会立即失效。确认轮换？'))return;try{const r=await api(`/api/v1/${kind}/${id}/rotate`,'POST',{});setReveal({title:'新令牌（仅显示一次）',token:r.token,url:r.subscription_url||'',deployCommand:r.deploy_command||''})}catch(e){setError(String(e))}};
  if(logged===null)return <div className="loading">正在连接面板…</div>;
  if(!logged)return <div className="login"><div className="login-card"><div className="brand-mark"><Shield size={28}/></div><p className="eyebrow">PRIVATE NETWORK CONTROL</p><h1>VPS Proxy Console</h1><p className="muted">登录后管理节点、代理流量与个人订阅。</p><form onSubmit={async e=>{e.preventDefault();try{await api('/api/v1/login','POST',{password});setPassword('');await refresh()}catch{setError('密码错误或尝试次数过多')}}}><label>管理员密码</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus placeholder="输入管理员密码"/><button className="primary full">登录控制台 <ChevronRight size={18}/></button></form>{error&&<div className="error">{error}</div>}</div><div className="login-footer">自托管 · 私有部署 · 多节点统一管理</div></div>;
  const list=(kind:Kind)=>collections[kind];
  const addButton=(kind:Kind)=><button className="primary" onClick={()=>setDialog({kind})}><Plus size={16}/>新增{plural[kind]}</button>;
  return <div className="shell">
    <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><span className="brand-mark small"><Shield size={20}/></span><div><strong>VPS Proxy</strong><small>CONTROL CONSOLE</small></div></div><div className="side-caption">工作空间</div><nav>{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setMobile(false);setError('')}}><n.icon size={18}/><span>{n.label}</span>{page===n.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="status-mini"><span className="pulse"/> 控制面板运行中</div><button className="logout" onClick={async()=>{await api('/api/v1/logout','POST',{});setLogged(false)}}><LogOut size={16}/>退出登录</button></div></aside>
    <main className="main"><header className="topbar"><button className="icon mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={22}/></button><div className="breadcrumb">工作空间 <ChevronRight size={15}/> <strong>{nav.find(n=>n.id===page)?.label}</strong></div><div className="top-actions"><span className="revision">配置版本 #{state.revision}</span><button className="icon" title="刷新" onClick={refresh}><RefreshCw size={18}/></button></div></header>
      <div className="content">{error&&<div className="error banner"><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}
      {page==='overview'?<><div className="page-heading"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h1>你的代理网络，一目了然</h1><p className="muted">统一查看节点、协议、订阅和流量使用情况。</p></div><button className="secondary" onClick={refresh}><RefreshCw size={16}/>刷新数据</button></div><div className="stats"><Stat icon={Server} label="VPS 节点" value={list('nodes').length} sub={`${list('nodes').filter(n=>n.last_seen&&Date.now()-new Date(str(n.last_seen)).getTime()<90000).length} 台在线`}/><Stat icon={Globe2} label="入站协议" value={list('inbounds').filter(x=>x.enabled).length} sub="已启用监听"/><Stat icon={Users} label="订阅人员" value={list('people').length} sub={`${list('assignments').length} 个节点分配`}/><Stat icon={Activity} label="累计用量" value={bytes(list('people').reduce((a,p)=>a+Number(p.used_bytes||0),0))} sub="入口上行 + 下行"/></div><div className="grid-two"><section className="panel"><div className="panel-head"><div><h2>节点状态</h2><p>最近心跳与配置应用情况</p></div><button className="text-btn" onClick={()=>setPage('nodes')}>查看全部 <ChevronRight size={15}/></button></div>{list('nodes').length?list('nodes').slice(0,6).map(n=><div className="status-row" key={n.id}><div className="node-avatar"><Server size={18}/></div><div className="grow"><strong>{str(n.name)}</strong><small>{str(n.domain)}</small></div><Status node={n}/></div>):<Empty text="还没有节点。先添加一台 VPS。" action={()=>setDialog({kind:'nodes'})}/>}</section><section className="panel"><div className="panel-head"><div><h2>额度概览</h2><p>各人员累计使用情况</p></div><button className="text-btn" onClick={()=>setPage('people')}>管理人员 <ChevronRight size={15}/></button></div>{list('people').length?list('people').slice(0,6).map(p=><div className="usage-row" key={p.id}><div className="usage-title"><strong>{str(p.name)}</strong><span>{bytes(p.used_bytes)} / {Number(p.quota_bytes)?bytes(p.quota_bytes):'不限额'}</span></div><div className="progress"><div style={{width:`${Number(p.quota_bytes)?Math.min(100,Number(p.used_bytes||0)/Number(p.quota_bytes)*100):0}%`}}/></div></div>):<Empty text="添加人员后可单独设置额度与订阅。" action={()=>setDialog({kind:'people'})}/>}</section></div><div className="hint"><CircleHelp size={18}/><div><strong>快速开始</strong><p>依次添加 VPS 节点、入站协议与人员，再建立订阅分配。节点 Agent 连接后会自动领取配置。</p></div></div></>:
      <><div className="page-heading"><div><p className="eyebrow">{page.toUpperCase()}</p><h1>{nav.find(n=>n.id===page)?.label}</h1><p className="muted">{descriptions[page]}</p></div>{addButton(page as Kind)}</div><section className="panel table-panel"><div className="panel-head"><div><h2>{plural[page as Kind]}列表</h2><p>共 {list(page as Kind).length} 项</p></div></div>{list(page as Kind).length?<div className="table-wrap"><table><thead><tr>{columns[page].map(c=><th key={c}>{c}</th>)}<th className="right">操作</th></tr></thead><tbody>{list(page as Kind).map(item=><tr key={item.id}>{renderCells(page,item,label)}<td className="right actions"><button onClick={()=>setDialog({kind:page as Kind,item})}>编辑</button>{(page==='nodes'||page==='people')&&<button onClick={()=>rotate(page as 'nodes'|'people',item.id)}><KeyRound size={14}/>轮换令牌</button>}<button className="danger-text" onClick={()=>remove(page as Kind,item.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<Empty text={`还没有${plural[page as Kind]}。`} action={()=>setDialog({kind:page as Kind})}/>}</section>{page==='nodes'&&<div className="hint"><CircleHelp size={18}/><p>新增节点后会显示完整部署命令，复制到节点 VPS 执行即可；令牌和部署命令只在创建或轮换时显示。</p></div>}{page==='people'&&<div className="hint"><CircleHelp size={18}/><p>人员订阅令牌仅显示一次。轮换后旧链接立即失效；订阅内容只包含已分配且有效的入口。</p></div>}</>}
      </div>
    </main>
    {dialog&&<Editor key={dialog.item?.id||'new-'+dialog.kind} kind={dialog.kind} item={dialog.item} state={collections} onClose={()=>{setDialog(null);setError('')}} onSave={onSave} busy={busy} error={error}/>}
    {reveal&&<div className="overlay" onMouseDown={()=>setReveal(null)}><div className="reveal modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{reveal.title}</h2><button className="icon" onClick={()=>setReveal(null)}><X size={20}/></button></div><p className="muted">请立即保存以下信息，关闭后不会再次显示。</p>{reveal.deployCommand?<><p className="muted">在目标 Linux VPS 的终端粘贴以下命令。它会拉取代码、写入节点配置并下载预构建 Agent 镜像，无需在 VPS 编译 Go。</p><div className="script-head"><label>Agent 部署命令（预览已隐藏令牌）</label><button className="secondary" onClick={()=>navigator.clipboard.writeText(reveal.deployCommand)}><Copy size={15}/>复制完整命令</button></div><pre className="deploy-script">{reveal.deployCommand.replace(/^NODE_TOKEN=.*$/m,'NODE_TOKEN=••••••••')}</pre><p className="muted">复制按钮仍会复制真实令牌。仅在对应 VPS 上执行；若令牌被截图或外泄，请轮换后重新部署。</p></>:<><label>访问令牌</label><div className="copybox"><code>{reveal.token}</code><button onClick={()=>navigator.clipboard.writeText(reveal.token)}><Copy size={16}/></button></div>{reveal.url&&<><label>订阅链接</label><div className="copybox"><code>{reveal.url}</code><button onClick={()=>navigator.clipboard.writeText(reveal.url)}><Copy size={16}/></button></div><div className="qr"><QRCode value={reveal.url} size={152}/></div><p className="muted">Mihomo 格式：在链接末尾添加 <code>?format=mihomo</code></p></>}</>}<button className="primary full" onClick={()=>setReveal(null)}><Check size={16}/>我已保存</button></div></div>}
  </div>;
}

const descriptions:Record<string,string>={nodes:'管理入口和落地 VPS，查看 Agent 心跳与配置状态。',inbounds:'配置客户端入口与私网落地 SOCKS5/HTTP。',outbounds:'定义手动上游代理或面板管理的落地节点。',rules:'按用户、入口和目标匹配出口；数字越小越优先。',people:'为每个人设置总流量额度、到期时间和订阅。',assignments:'决定每个人可以使用哪些入口协议与节点。'};
const columns:Record<string,string[]>={nodes:['节点','公网域名','私网地址','状态','最近心跳'],people:['人员','额度','已用','到期','状态'],inbounds:['名称','节点','协议','监听','状态'],outbounds:['名称','节点','协议','目标'],rules:['优先级','节点','匹配用户 / 入站','目标','出口'],assignments:['人员','入站','凭据']};
function renderCells(page:string,x:Item,label:(k:Kind,id:unknown)=>string){switch(page){
  case 'nodes':return <><td><strong>{str(x.name)}</strong><small className="id">{x.id}</small></td><td>{str(x.domain)}</td><td>{str(x.private_ip)||'—'}</td><td><Status node={x}/></td><td>{date(x.last_seen)}</td></>;
  case 'people':return <><td><strong>{str(x.name)}</strong><small className="id">{x.id}</small></td><td>{Number(x.quota_bytes)?bytes(x.quota_bytes):'不限额'}</td><td>{bytes(x.used_bytes)}</td><td>{date(x.expires_at)}</td><td><span className={'badge '+(x.disabled?'bad':'good')}>{x.disabled?'已禁用':'有效'}</span></td></>;
  case 'inbounds':return <><td><strong>{str(x.name)}</strong><small className="id">{x.id}</small></td><td>{label('nodes',x.node_id)}</td><td><span className="badge neutral">{str(x.protocol)}</span></td><td>{str(x.listen)||'0.0.0.0'}:{str(x.port)}</td><td><span className={'badge '+(x.enabled?'good':'neutral')}>{x.enabled?'启用':'停用'}</span></td></>;
  case 'outbounds':return <><td><strong>{str(x.name)}</strong></td><td>{label('nodes',x.node_id)}</td><td>{str(x.protocol).toUpperCase()}</td><td>{x.landing_inbound_id?`落地：${label('inbounds',x.landing_inbound_id)}`:`${str(x.host)}:${str(x.port)}`}</td></>;
  case 'rules':return <><td><strong>{str(x.position)}</strong></td><td>{label('nodes',x.node_id)}</td><td>{x.person_id?label('people',x.person_id):'所有用户'} / {x.inbound_id?label('inbounds',x.inbound_id):'所有入口'}</td><td>{[...(Array.isArray(x.domains)?x.domains:[]),...(Array.isArray(x.cidrs)?x.cidrs:[])].join(', ')||'所有目标'}</td><td>{x.outbound_id==='direct'?'直连':x.outbound_id==='block'?'阻断':label('outbounds',x.outbound_id)}</td></>;
  case 'assignments':return <><td><strong>{label('people',x.person_id)}</strong></td><td>{label('inbounds',x.inbound_id)}</td><td><code className="credential">{str(x.credential)}</code></td></>;
  default:return null;
}}
function Status({node}:{node:Item}){const online=!!node.last_seen&&Date.now()-new Date(str(node.last_seen)).getTime()<90000;return <span className={'badge '+(node.apply_error?'bad':online?'good':'neutral')}><span className="badge-dot"/>{node.apply_error?'配置错误':online?'在线':'离线'}</span>}
function Stat({icon:Icon,label,value,sub}:{icon:React.ComponentType<{size?:number}>,label:string,value:string|number,sub:string}){return <div className="stat"><div className="stat-icon"><Icon size={20}/></div><p>{label}</p><strong>{value}</strong><small>{sub}</small></div>}
function Empty({text,action}:{text:string,action:()=>void}){return <div className="empty"><div className="empty-icon"><Plus size={24}/></div><p>{text}</p><button className="text-btn" onClick={action}>立即添加 <ChevronRight size={15}/></button></div>}

function Editor({kind,item,state,onClose,onSave,busy,error}:{kind:Kind,item?:Item,state:Record<Kind,Item[]>,onClose:()=>void,onSave:(k:Kind,i:Item|undefined,b:Record<string,unknown>)=>void,busy:boolean,error:string}){
  const opt=(items:Item[],name='name')=>items.map(x=>({value:x.id,label:str(x[name]||x.id)}));
  const fields:Field[]=kind==='nodes'?[{key:'name',label:'节点名称'},{key:'domain',label:'公网域名',hint:'已解析到 VPS，例如 node.example.com'},{key:'private_ip',label:'私网 / 隧道 IP',hint:'落地节点需要此地址；支持 RFC1918 或 100.64/10'}]:
    kind==='people'?[{key:'name',label:'称呼'},{key:'quota_gb',label:'总额度（GB，0 为不限）',type:'number'},{key:'expires_at',label:'到期时间',type:'datetime-local'},{key:'disabled',label:'禁用此人',type:'checkbox'}]:
    kind==='inbounds'?[{key:'node_id',label:'所属节点',type:'select',options:opt(state.nodes)},{key:'name',label:'入口名称'},{key:'protocol',label:'协议',type:'select',options:['vless-tls','vless-reality','trojan-tls','ss','vmess-ws-tls','socks','http'].map(value=>({value,label:value}))},{key:'listen',label:'监听地址',hint:'公网入口留空；SOCKS/HTTP 填节点私网 IP'},{key:'port',label:'端口',type:'number'},{key:'domain',label:'域名 / SNI',hint:'TLS/REALITY/WS 使用'},{key:'path',label:'WebSocket 路径',hint:'仅 VMess WS，默认 /ws'},{key:'reality_dest',label:'REALITY 目标',hint:'例如 example.com:443'},{key:'reality_private_key',label:'REALITY 私钥',hint:'创建时可留空自动生成'},{key:'reality_public_key',label:'REALITY 公钥'},{key:'reality_short_id',label:'REALITY Short ID'},{key:'service_user',label:'落地账号',hint:'SOCKS/HTTP 创建时可留空自动生成'},{key:'service_password',label:'落地密码',type:'password'},{key:'ss_server_key',label:'Shadowsocks 服务密码',type:'password'},{key:'enabled',label:'启用',type:'checkbox'}]:
    kind==='outbounds'?[{key:'node_id',label:'入口节点',type:'select',options:opt(state.nodes)},{key:'name',label:'出口名称'},{key:'protocol',label:'协议',type:'select',options:[{value:'socks',label:'SOCKS5'},{value:'http',label:'HTTP'}]},{key:'landing_inbound_id',label:'面板管理的落地入口',type:'select',options:[{value:'',label:'手动上游'},...opt(state.inbounds.filter(x=>x.protocol==='socks'||x.protocol==='http'))]},{key:'host',label:'上游地址',hint:'手动上游时填写'},{key:'port',label:'上游端口',type:'number'},{key:'username',label:'上游账号'},{key:'password',label:'上游密码',type:'password'}]:
    kind==='rules'?[{key:'node_id',label:'应用节点',type:'select',options:opt(state.nodes)},{key:'position',label:'顺序（越小越优先）',type:'number'},{key:'person_id',label:'限定人员',type:'select',options:[{value:'',label:'所有人员'},...opt(state.people)]},{key:'inbound_id',label:'限定入站',type:'select',options:[{value:'',label:'所有入站'},...opt(state.inbounds)]},{key:'domains',label:'目标域名规则',type:'textarea',hint:'每行一条，例如 domain:example.com 或 geosite:category-ads-all'},{key:'cidrs',label:'目标 IP / CIDR',type:'textarea',hint:'每行一条，例如 10.0.0.0/8 或 geoip:cn'},{key:'outbound_id',label:'选择出口',type:'select',options:[{value:'direct',label:'直连'},{value:'block',label:'阻断'},...opt(state.outbounds)]}]:
    [{key:'person_id',label:'人员',type:'select',options:opt(state.people)},{key:'inbound_id',label:'分配入口',type:'select',options:opt(state.inbounds.filter(x=>!['socks','http'].includes(str(x.protocol))))}];
  const initial:Record<string,unknown>={...item};if(kind==='people'){initial.quota_gb=Number(item?.quota_bytes||0)/1024**3;initial.expires_at=item?.expires_at?new Date(str(item.expires_at)).toISOString().slice(0,16):''}if(kind==='inbounds'&&!item)initial.enabled=true;
  const [form,setForm]=useState<Record<string,unknown>>(initial);
  const change=(key:string,val:unknown)=>setForm(f=>({...f,[key]:val}));
  const submit=(e:React.FormEvent)=>{e.preventDefault();const body={...form};if(kind==='people'){body.quota_bytes=Math.round(Number(body.quota_gb||0)*1024**3);delete body.quota_gb;body.expires_at=body.expires_at?new Date(str(body.expires_at)).toISOString():null;delete body.used_bytes}if(kind==='rules'){body.domains=str(body.domains).split('\n').map(x=>x.trim()).filter(Boolean);body.cidrs=str(body.cidrs).split('\n').map(x=>x.trim()).filter(Boolean)}if(kind==='inbounds'){body.port=Number(body.port);if(!body.listen&&['socks','http'].includes(str(body.protocol))){body.listen=state.nodes.find(x=>x.id===body.node_id)?.private_ip||''}}if(kind==='outbounds')body.port=Number(body.port||0);if(kind==='rules')body.position=Number(body.position||0);delete body.id;onSave(kind,item,body)};
  return <div className="overlay" onMouseDown={onClose}><div className="modal editor" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">{item?'EDIT':'CREATE'} RESOURCE</p><h2>{item?'编辑':'新增'}{plural[kind]}</h2></div><button className="icon" onClick={onClose}><X size={20}/></button></div><form onSubmit={submit}><div className="form-grid">{fields.map(f=><div className={'field '+(f.type==='textarea'?'wide':'')} key={f.key}><label htmlFor={f.key}>{f.label}</label>{f.type==='checkbox'?<label className="switch-row"><input id={f.key} type="checkbox" checked={!!form[f.key]} onChange={e=>change(f.key,e.target.checked)}/><span>{form[f.key]?'已启用':'未启用'}</span></label>:f.type==='select'?<select id={f.key} value={str(form[f.key])} onChange={e=>change(f.key,e.target.value)}><option value="">请选择</option>{f.options?.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea id={f.key} rows={3} value={Array.isArray(form[f.key])?(form[f.key] as string[]).join('\n'):str(form[f.key])} onChange={e=>change(f.key,e.target.value)}/>:<input id={f.key} type={f.type||'text'} value={str(form[f.key])} onChange={e=>change(f.key,e.target.value)} min={f.type==='number'?0:undefined}/>} {f.hint&&<small>{f.hint}</small>}</div>)}</div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?'保存中…':'保存配置'}</button></div></form></div></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
